DROP DATABASE IF EXISTS usertest;
CREATE DATABASE usertest;
USE usertest;

CREATE TABLE user
(
    id INTEGER NOT NULL AUTO_INCREMENT,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    PRIMARY KEY(id)
);